# Generated by Django 3.0.7 on 2020-08-16 23:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(help_text='uuid is required', unique=True, validators=[django.core.validators.MaxLengthValidator, django.core.validators.MinLengthValidator], verbose_name='uuid')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='createdAt')),
                ('deletedAt', models.DateTimeField(blank=True, null=True, verbose_name='deletedAt')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='updatedAt')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Discipline',
                'verbose_name_plural': 'Disciplines',
                'db_table': 'Discipline',
            },
        ),
        migrations.CreateModel(
            name='PaperType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(help_text='uuid is required', unique=True, validators=[django.core.validators.MaxLengthValidator, django.core.validators.MinLengthValidator], verbose_name='uuid')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='createdAt')),
                ('deletedAt', models.DateTimeField(blank=True, null=True, verbose_name='deletedAt')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='updatedAt')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'PaperType',
                'verbose_name_plural': 'PaperTypes',
                'db_table': 'PaperType',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(help_text='uuid is required', unique=True, validators=[django.core.validators.MaxLengthValidator, django.core.validators.MinLengthValidator], verbose_name='uuid')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='createdAt')),
                ('deletedAt', models.DateTimeField(blank=True, null=True, verbose_name='deletedAt')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='updatedAt')),
                ('rate', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(limit_value=10, message='Rating cannot be more than ten.')])),
            ],
            options={
                'verbose_name': 'Rating',
                'verbose_name_plural': 'Ratings',
                'db_table': 'Rating',
            },
        ),
    ]
