# Generated by Django 3.1.1 on 2020-09-03 16:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(help_text='uuid is required', unique=True, validators=[django.core.validators.MaxLengthValidator, django.core.validators.MinLengthValidator], verbose_name='uuid')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='createdAt')),
                ('deletedAt', models.DateTimeField(null=True, verbose_name='deletedAt')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='updatedAt')),
                ('title', models.CharField(help_text='Title of the Alert.', max_length=30, unique=True)),
                ('description', models.TextField(help_text='Description for the Alert.')),
                ('status', models.CharField(choices=[(None, 'Unknown'), ('ACTIVE', 'ACTIVE'), ('REVIEW', 'REVIEW'), ('INACTIVE', 'INACTIVE')], default='REVIEW', help_text='Status of the Alert.', max_length=10)),
                ('_type', models.CharField(choices=[(None, 'Unknown'), ('INFORMATIVE', 'INFORMATIVE'), ('UI', 'UI')], default='INFORMATIVE', help_text='Type of the alert being created.', max_length=12)),
                ('_from', models.DateTimeField(auto_now_add=True, help_text='Active from.', null=True)),
                ('to', models.DateTimeField(auto_now=True, help_text='Active until.')),
                ('is_active', models.BooleanField(default=True, help_text='Deleted or active.')),
            ],
            options={
                'verbose_name': 'Alert',
                'verbose_name_plural': 'Alerts',
                'db_table': 'Alert',
                'ordering': ('-createdAt',),
            },
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(help_text='uuid is required', unique=True, validators=[django.core.validators.MaxLengthValidator, django.core.validators.MinLengthValidator], verbose_name='uuid')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='createdAt')),
                ('deletedAt', models.DateTimeField(null=True, verbose_name='deletedAt')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='updatedAt')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('price', models.CharField(default=0, max_length=10)),
                ('level', models.CharField(choices=[(None, 'Unknown'), ('ALL', 'ALL'), ('HIGHSCHOOL', 'HIGHSCHOOL'), ('PHD', 'PHD'), ('GRADUATE', 'GRADUATE'), ('UNDERGRADUATE_1_2', 'UNDERGRADUATE_1_2'), ('UNDERGRADUATE_3_4', 'UNDERGRADUATE_3_4')], default='HIGHSCHOOL', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Discipline',
                'verbose_name_plural': 'Disciplines',
                'db_table': 'Discipline',
                'ordering': ('-createdAt',),
            },
        ),
        migrations.CreateModel(
            name='PaperType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(help_text='uuid is required', unique=True, validators=[django.core.validators.MaxLengthValidator, django.core.validators.MinLengthValidator], verbose_name='uuid')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='createdAt')),
                ('deletedAt', models.DateTimeField(null=True, verbose_name='deletedAt')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='updatedAt')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('price', models.CharField(default=0, max_length=10)),
                ('level', models.CharField(choices=[(None, 'Unknown'), ('ALL', 'ALL'), ('HIGHSCHOOL', 'HIGHSCHOOL'), ('PHD', 'PHD'), ('GRADUATE', 'GRADUATE'), ('UNDERGRADUATE_1_2', 'UNDERGRADUATE_1_2'), ('UNDERGRADUATE_3_4', 'UNDERGRADUATE_3_4')], default='HIGHSCHOOL', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'PaperType',
                'verbose_name_plural': 'PaperTypes',
                'db_table': 'PaperType',
                'ordering': ('-createdAt',),
            },
        ),
    ]
