# Generated by Django 3.0.7 on 2020-08-20 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='papertype',
            name='admin',
            field=models.ForeignKey(limit_choices_to={'is_active': True, 'user_type': 'MASTER'}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AddField(
            model_name='discipline',
            name='admin',
            field=models.ForeignKey(limit_choices_to={'is_active': True, 'user_type': 'MASTER'}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
