# Generated by Django 3.1.1 on 2020-09-03 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='papertype',
            name='admin',
            field=models.ForeignKey(limit_choices_to={'is_active': True, 'user_type': 'MASTER'}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AddField(
            model_name='discipline',
            name='admin',
            field=models.ForeignKey(limit_choices_to={'is_active': True, 'user_type': 'MASTER'}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AddField(
            model_name='alert',
            name='admin',
            field=models.ForeignKey(help_text='Admin creating the alert.', limit_choices_to={'is_active': True, 'is_staff': True, 'is_superuser': True, 'user_type': 'MASTER'}, on_delete=django.db.models.deletion.PROTECT, related_name='admin', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AddField(
            model_name='alert',
            name='deleted_by',
            field=models.ForeignKey(help_text='Admin deleting the alert.', limit_choices_to={'is_active': True, 'is_staff': True, 'is_superuser': True, 'user_type': 'MASTER'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deleted_by', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
