# Generated by Django 3.1.1 on 2020-09-05 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200903_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='valid',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='papertype',
            name='valid',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
