# Generated by Django 3.1 on 2020-08-24 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200822_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='level',
            field=models.CharField(choices=[(None, 'Unknown'), ('HIGHSCHOOL', 'HIGHSCHOOL'), ('PHD', 'PHD'), ('GRADUATE', 'GRADUATE'), ('UNDERGRADUATE_1_2', 'UNDERGRADUATE_1_2'), ('UNDERGRADUATE_3_4', 'UNDERGRADUATE_3_4')], default='HIGHSCHOOL', max_length=20),
        ),
        migrations.AddField(
            model_name='discipline',
            name='price',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='papertype',
            name='level',
            field=models.CharField(choices=[(None, 'Unknown'), ('HIGHSCHOOL', 'HIGHSCHOOL'), ('PHD', 'PHD'), ('GRADUATE', 'GRADUATE'), ('UNDERGRADUATE_1_2', 'UNDERGRADUATE_1_2'), ('UNDERGRADUATE_3_4', 'UNDERGRADUATE_3_4')], default='HIGHSCHOOL', max_length=20),
        ),
        migrations.AddField(
            model_name='papertype',
            name='price',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
