# Generated by Django 3.0.7 on 2020-08-14 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200814_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_smart_paper',
        ),
        migrations.AlterField(
            model_name='order',
            name='charts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='cost',
            field=models.PositiveIntegerField(default=0, help_text='The cost of a paper'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pages',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='powerpoint',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='progressive',
            field=models.BooleanField(default=False, help_text='Number of powerpoints requested by client'),
        ),
        migrations.AlterField(
            model_name='order',
            name='smart',
            field=models.BooleanField(default=False, help_text='Whether an order is  a smart paper.'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sources',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
