# Generated by Django 3.0.7 on 2020-08-11 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200810_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='createdAt'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='deletedAt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='deletedAt'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='updateAt',
            field=models.DateTimeField(auto_now=True, verbose_name='updateAt'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='createdAt'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='deletedAt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='deletedAt'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='updateAt',
            field=models.DateTimeField(auto_now=True, verbose_name='updateAt'),
        ),
        migrations.AlterField(
            model_name='order',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='createdAt'),
        ),
        migrations.AlterField(
            model_name='order',
            name='deletedAt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='deletedAt'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updateAt',
            field=models.DateTimeField(auto_now=True, verbose_name='updateAt'),
        ),
        migrations.AlterField(
            model_name='orderfiles',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='createdAt'),
        ),
        migrations.AlterField(
            model_name='orderfiles',
            name='deletedAt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='deletedAt'),
        ),
        migrations.AlterField(
            model_name='orderfiles',
            name='updateAt',
            field=models.DateTimeField(auto_now=True, verbose_name='updateAt'),
        ),
        migrations.AlterField(
            model_name='papertype',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='createdAt'),
        ),
        migrations.AlterField(
            model_name='papertype',
            name='deletedAt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='deletedAt'),
        ),
        migrations.AlterField(
            model_name='papertype',
            name='updateAt',
            field=models.DateTimeField(auto_now=True, verbose_name='updateAt'),
        ),
    ]
