# Generated by Django 3.0.7 on 2020-08-14 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_auto_20200814_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='academic',
            field=models.CharField(choices=[('HIGHSCHOOL', 'HIGHSCHOOL'), ('PHD', 'PHD'), ('GRADUATE', 'GRADUATE'), ('UNDERGRADUATE_1_2', 'UNDERGRADUATE_1_2'), ('UNDERGRADUATE_3_4', 'UNDERGRADUATE_3_4')], default='HIGHSCHOOL', help_text='Clients academic level', max_length=200, verbose_name='academic'),
        ),
        migrations.AlterField(
            model_name='order',
            name='charts',
            field=models.PositiveIntegerField(default=0, help_text='Number of charts requested in the current order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='deadline',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='The deadline of this order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='discipline',
            field=models.CharField(help_text='This orders discipline', max_length=200, verbose_name='discipline'),
        ),
        migrations.AlterField(
            model_name='order',
            name='format',
            field=models.CharField(choices=[('MLA', 'MLA'), ('CHICAGO/TURABIAN', 'CHICAGO/TURABIAN'), ('APA7', 'APA7'), ('APA6', 'APA6')], default='MLA', help_text='Format chosen by client for this order, eg. MLA, APA6...', max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='instructions',
            field=models.TextField(help_text='This paper instructions'),
        ),
        migrations.AlterField(
            model_name='order',
            name='native',
            field=models.BooleanField(default=False, help_text='To a assign a native writer for the current order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pages',
            field=models.PositiveIntegerField(default=0, help_text='Number of pages requested in the current order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='paper_type',
            field=models.CharField(help_text='This order paper type', max_length=200, verbose_name='paper_type'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payments_url',
            field=models.URLField(blank=True, help_text='A payment url to verify user paid the order', null=True, unique=True, verbose_name='payment_url'),
        ),
        migrations.AlterField(
            model_name='order',
            name='powerpoint',
            field=models.PositiveIntegerField(default=0, help_text='Number of powerpoints requested in the current order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='preference',
            field=models.CharField(choices=[('BEST AVAILABLE', 'BEST AVAILABLE'), ('ADVANCED', 'ADVANCED'), ('TOP10', 'TOP10'), ('TOP25', 'TOP25')], default='BEST AVAILABLE', help_text='The writer preference a the client chose for this order.', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='progressive',
            field=models.BooleanField(default=False, help_text='If order is a progressive delivery'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sources',
            field=models.PositiveIntegerField(default=0, help_text='Number of sources requested in the current order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='spacing',
            field=models.CharField(choices=[('SINGLE', 'SINGLE'), ('DOUBLE', 'DOUBLE')], default='SINGLE', help_text='Whether order is single or double spaced', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'DRAFT'), ('REVISION', 'REVISION'), ('ACTIVE', 'ACTIVE'), ('FINISHED', 'FINISHED'), ('CANCELED', 'CANCELED'), ('DISPUTE', 'DISPUTE')], default='ACTIVE', help_text='Where an order belongs to ether active, deleted, or ..', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='title',
            field=models.CharField(help_text='This orders title', max_length=200, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(default=0, help_text='Client Placing the order', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
