# Generated by Django 3.1 on 2020-08-24 18:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_auto_20200824_1855'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discipline',
            options={'ordering': ('-createdAt',), 'verbose_name': 'Discipline', 'verbose_name_plural': 'Disciplines'},
        ),
        migrations.AlterModelOptions(
            name='papertype',
            options={'ordering': ('-createdAt',), 'verbose_name': 'PaperType', 'verbose_name_plural': 'PaperTypes'},
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(help_text='uuid is required', unique=True, validators=[django.core.validators.MaxLengthValidator, django.core.validators.MinLengthValidator], verbose_name='uuid')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='createdAt')),
                ('deletedAt', models.DateTimeField(null=True, verbose_name='deletedAt')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='updatedAt')),
                ('title', models.CharField(help_text='Title of the Alert.', max_length=30)),
                ('description', models.TextField(help_text='Description for the Alert.')),
                ('status', models.CharField(choices=[(None, 'Unknown'), ('ACTIVE', 'ACTIVE'), ('REVIEW', 'REVIEW'), ('INACTIVE', 'INACTIVE')], default='REVIEW', help_text='Status of the Alert.', max_length=10)),
                ('_type', models.CharField(choices=[(None, 'Unknown'), ('INFORMATIVE', 'INFORMATIVE'), ('UI', 'UI')], default='INFORMATIVE', help_text='Type of the alert being created.', max_length=12)),
                ('_from', models.DateTimeField()),
                ('to', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('admin', models.ForeignKey(help_text='Admin creating the alert.', limit_choices_to={'is_active': True, 'is_staff': True, 'is_superuser': True, 'user_type': 'MASTER'}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'verbose_name': 'Alert',
                'verbose_name_plural': 'Alerts',
                'db_table': 'Alert',
                'ordering': ('-createdAt',),
            },
        ),
    ]
