# Generated by Django 3.0.7 on 2020-08-12 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200813_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_paper',
            field=models.BooleanField(default=True, help_text='Whether a paper id deleted/canceled.'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cost',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
