# Generated by Django 3.0.7 on 2020-08-12 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200813_0115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='paper_instructions',
            new_name='instructions',
        ),
    ]
