# Generated by Django 3.0.7 on 2020-08-15 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200814_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='additional_materials',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderFiles',
        ),
    ]
