# Generated by Django 3.1 on 2020-08-24 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_auto_20200824_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='deleted_by',
            field=models.ForeignKey(help_text='Admin deleting the alert.', limit_choices_to={'is_active': True, 'is_staff': True, 'is_superuser': True, 'user_type': 'MASTER'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deleted_by', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='_from',
            field=models.DateTimeField(help_text='Active from.'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='admin',
            field=models.ForeignKey(help_text='Admin creating the alert.', limit_choices_to={'is_active': True, 'is_staff': True, 'is_superuser': True, 'user_type': 'MASTER'}, on_delete=django.db.models.deletion.PROTECT, related_name='admin', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Deleted or active.'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='to',
            field=models.DateTimeField(help_text='Active until.'),
        ),
    ]
