# Generated by Django 3.1.1 on 2020-09-07 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200906_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='_from',
            field=models.DateTimeField(auto_now_add=True, help_text='Active from.', null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='to',
            field=models.DateTimeField(auto_now=True, help_text='Active until.', null=True),
        ),
    ]
