# Generated by Django 3.0.7 on 2020-08-13 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200813_0128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='paper_format',
            new_name='format',
        ),
    ]
