# Generated by Django 3.1 on 2020-08-24 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200825_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='to',
            field=models.DateTimeField(auto_now=True, help_text='Active until.'),
        ),
    ]
