# Generated by Django 3.1 on 2020-08-25 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200825_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='title',
            field=models.CharField(help_text='Title of the Alert.', max_length=30, unique=True),
        ),
    ]
