# Generated by Django 3.0.7 on 2020-08-10 16:27

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='createdAt',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='createdAt'),
        ),
        migrations.AddField(
            model_name='user',
            name='deletedAt',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='deletedAt'),
        ),
        migrations.AddField(
            model_name='user',
            name='updateAt',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='updateAt'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.MaxLengthValidator(limit_value=254, message='Email is too long')], verbose_name='email'),
        ),
    ]
