# Generated by Django 3.1 on 2020-08-24 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_auto_20200822_2212'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avatar',
            options={'ordering': ('-createdAt',), 'verbose_name': 'Avatar', 'verbose_name_plural': 'Avatars'},
        ),
        migrations.AlterOrderWithRespectTo(
            name='avatar',
            order_with_respect_to=None,
        ),
    ]
