# Generated by Django 3.1.1 on 2020-09-06 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_auto_20200904_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaults',
            name='academic',
            field=models.CharField(choices=[(None, 'Unknown'), ('HIGHSCHOOL', 'HIGHSCHOOL'), ('PHD', 'PHD'), ('GRADUATE', 'GRADUATE'), ('UNDERGRADUATE_1_2', 'UNDERGRADUATE_1_2'), ('UNDERGRADUATE_3_4', 'UNDERGRADUATE_3_4')], default='Unknown', help_text='Client default academic level', max_length=17),
        ),
    ]
