# Generated by Django 3.0.7 on 2020-08-15 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='order',
        ),
        migrations.RemoveField(
            model_name='order',
            name='card',
        ),
        migrations.AddField(
            model_name='order',
            name='additional_materials',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_deleted': False}, to='order.Files'),
        ),
    ]
