# Generated by Django 3.1 on 2020-08-24 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='files',
            options={'ordering': ('-createdAt',), 'verbose_name': 'File', 'verbose_name_plural': 'Files'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ('-createdAt',), 'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-createdAt',), 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='writer',
            options={'ordering': ('-createdAt',), 'verbose_name': 'Writer', 'verbose_name_plural': 'Writers'},
        ),
        migrations.AlterOrderWithRespectTo(
            name='order',
            order_with_respect_to=None,
        ),
    ]
