# Generated by Django 3.1.1 on 2020-09-04 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='copy',
            field=models.BooleanField(default=False, help_text='Whether to provide a copy of the sources.'),
        ),
    ]
