# Generated by Django 3.0.7 on 2020-08-17 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0002_auto_20200817_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='academic',
            field=models.CharField(choices=[(None, 'Unknown'), ('HIGHSCHOOL', 'HIGHSCHOOL'), ('PHD', 'PHD'), ('GRADUATE', 'GRADUATE'), ('UNDERGRADUATE_1_2', 'UNDERGRADUATE_1_2'), ('UNDERGRADUATE_3_4', 'UNDERGRADUATE_3_4')], default='HIGHSCHOOL', help_text='Clients academic level', max_length=17, verbose_name='academic'),
        ),
        migrations.AlterField(
            model_name='order',
            name='additional_materials',
            field=models.ManyToManyField(limit_choices_to={'is_deleted': False}, null=True, to='order.Files'),
        ),
        migrations.AlterField(
            model_name='order',
            name='format',
            field=models.CharField(choices=[(None, 'Unknown'), ('MLA', 'MLA'), ('CHICAGO/TURABIAN', 'CHICAGO/TURABIAN'), ('APA7', 'APA7'), ('APA6', 'APA6')], default='MLA', help_text='Format chosen by client for this order, eg. MLA, APA6...', max_length=16),
        ),
        migrations.AlterField(
            model_name='order',
            name='payments_url',
            field=models.URLField(help_text='A payment url to verify user paid the order', null=True, unique=True, verbose_name='payment_url'),
        ),
        migrations.AlterField(
            model_name='order',
            name='smart',
            field=models.BooleanField(default=False, help_text='Whether an order is  a smart paper.', verbose_name='is_smart'),
        ),
        migrations.AlterField(
            model_name='order',
            name='spacing',
            field=models.CharField(choices=[(None, 'Unknown'), ('SINGLE', 'SINGLE'), ('DOUBLE', 'DOUBLE')], default='SINGLE', help_text='Whether order is single or double spaced', max_length=6),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(default=None, help_text='Client Placing the order', limit_choices_to={'is_active': True, 'is_staff': False}, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='order',
            name='writer',
            field=models.ForeignKey(default=None, help_text='Who is assigned to work on this order', limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='order.Writer', to_field='username', verbose_name='writer'),
        ),
        migrations.AlterOrderWithRespectTo(
            name='order',
            order_with_respect_to='user',
        ),
    ]
