# Generated by Django 3.1.1 on 2020-09-04 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_copy'),
    ]

    operations = [
        migrations.AddField(
            model_name='writer',
            name='bio',
            field=models.TextField(null=True),
        ),
    ]
