# Generated by Django 3.0.7 on 2020-08-17 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20200817_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='additional_materials',
            field=models.ManyToManyField(limit_choices_to={'is_deleted': False}, to='order.Files'),
        ),
    ]
