# Generated by Django 3.1 on 2020-08-25 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0003_order_deleted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='created',
            field=models.ForeignKey(default=None, help_text='Which admin created', limit_choices_to={'is_active': True, 'user_type': ['MASTER', 'ADMIN']}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created', related_query_name='creator', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(default=None, help_text='User to be sent this notification', limit_choices_to={'is_active': True, 'is_staff': False, 'is_superuser': False, 'user_type': 'USER'}, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
