# Generated by Django 3.1.1 on 2020-09-07 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20200906_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='writer',
            name='last_name',
        ),
    ]
