# Generated by Django 3.1 on 2020-08-25 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_cancel'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
