# Generated by Django 3.1 on 2020-08-25 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_cancel_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancel',
            name='order',
            field=models.ForeignKey(limit_choices_to={'is_approved': False, 'is_paper': True}, on_delete=django.db.models.deletion.PROTECT, to='order.order', to_field='uuid'),
        ),
    ]
